do all repeats in 1 job, match config of OSG job

diff --git a/main b/main
--- a/main
+++ b/main
@@ -1,5 +1,5 @@
 #!/bin/bash
-#PBS -l nodes=1:ppn=1,vmem=4gb,walltime=01:00:00
+#PBS -l nodes=1:ppn=1,vmem=4gb,walltime=04:00:00
 #PBS -N mrtrix3_act_rep
 #PBS -V
 
@@ -12,10 +12,10 @@ echo "Tracking data..."
 time singularity exec -e docker://brainlife/mrtrix3:$tag ./mrtrix3_tracking.sh
 
 ## check for the output for success
-if [ -f out/track.tck ]; then
-    exit 0
-else
-    echo "Final tractography file missing."
-    exit 1
-fi
+# if [ -f out/track.tck ]; then
+#     exit 0
+# else
+#     echo "Final tractography file missing."
+#     exit 1
+# fi
 
